include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_double_and_int_checks
    - avoid_redundant_argument_values
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - join_return_with_assignment
    - only_throw_errors
    - prefer_const_constructors_in_immutables
    - prefer_expression_function_bodies
    - prefer_final_in_for_each
    - prefer_final_locals
    - sort_constructors_first
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_string_buffers
